# Generated by Django 3.2.5 on 2021-08-18 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('users', '0002_auto_20210818_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, limit_choices_to={'colleges': models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='college.college')}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='college.branch'),
        ),
    ]
